- name: "play : test play"
  hosts: all
  remote_user: root
  gather_facts: no
  vars:
    vvv: 'True'
  tasks:
    - name: pwd
      shell: pwd
      register: out
    - debug: msg={{out.stdout_lines}}

